version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: trendplus-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
